version: '3'
services:
  postgresql:
    image: postgres:17
    command: postgres -c 'max_connections=100'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: sale_time_db